=== appworks-lab/AppToolkit/toolkits.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema for the toolkit manifest, detailing the installation process for various tools on Mac/Windows/Linux OS.",
  "type": "object",
  "properties": {
    "description": {
      "type": "string",
      "description": "Brief overview of the toolkit manifest."
    },
    "version": {
      "type": "string",
      "description": "Version of the toolkit manifest."
    },
    "author": {
      "type": "string",
      "description": "Author of the toolkit manifest."
    },
    "tools": {
      "type": "array",
      "description": "The list of tools to be installed by the toolkit.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the tool."
          },
          "description": {
            "type": "string",
            "description": "Brief description of the tool."
          },
          "installations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "os": {
                  "type": "string",
                  "enum": [
                    "macos",
                    "windows",
                    "linux"
                  ],
                  "description": "Operating system for which the tool is to be installed."
                },
                "arch": {
                  "type": "string",
                  "enum": [
                    "x86_64",
                    "aarch64"
                  ],
                  "description": "Architecture for which the tool is to be installed."
                },
                "id": {
                  "type": "string",
                  "description": "The ID of the tool which is used to identify whether the tool is installed or not. For example, 'brew' for Homebrew, 'Visual Studio Code.app' for Visual Studio Code, etc."
                },
                "type": {
                  "type": "string",
                  "enum": [
                    "dmg",
                    "zip",
                    "exe",
                    "shell",
                    "deb"
                  ],
                  "description": "Type of the installation tool. Toolkit will use different methods to install the package based on the type."
                },
                "source": {
                  "type": "string",
                  "description": "The Source which how to download and install the tool."
                },
                "postInstall": {
                  "type": "string",
                  "description": "The command to run after the installation of the tool."
                }
              },
              "required": [
                "os",
                "id",
                "type",
                "source"
              ]
            }
          }
        }
      }
    }
  }
}

=== appworks-lab/AppToolkit/toolkits.manifest.json
{
  "$schema": "./toolkits.schema.json",
  "author": "luhc228 <luhengchang228@126.com>",
  "version": "0.0.0",
  "description": "A toolkit schema for web development.",
  "tools": [
    {
      "name": "Visual Studio Code",
      "description": "Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications.",
      "installations": [
        {
          "os": "macos",
          "arch": "x86_64",
          "type": "zip",
          "id": "Visual Studio Code.app",
          "source": "https://update.code.visualstudio.com/1.89.1/darwin/stable"
        },
        {
          "os": "macos",
          "arch": "aarch64",
          "type": "zip",
          "id": "Visual Studio Code.app",
          "source": "https://update.code.visualstudio.com/1.89.1/darwin-arm64/stable"
        },
        {
          "os": "windows",
          "arch": "x86_64",
          "type": "exe",
          "id": "Microsoft Visual Studio Code (User)",
          "source": "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
        },
        {
          "os": "linux",
          "arch": "x86_64",
          "type": "deb",
          "id": "",
          "source": "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
        }
      ]
    },
    {
      "name": "Google Chrome",
      "description": "Google Chrome is a fast, secure, and free web browser, built for the modern web.",
      "installations": [
        {
          "os": "macos",
          "type": "dmg",
          "id": "Google Chrome.app",
          "source": "https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg"
        },
        {
          "os": "windows",
          "arch": "x86_64",
          "type": "exe",
          "id": "Google Chrome",
          "source": "https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B92DB07C1-7ED7-8613-94E0-B27FEB01BC15%7D%26lang%3Den%26browser%3D4%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-statsdef_1%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe"
        }
      ]
    },
    {
      "name": "fnm",
      "description": "Fast Node Manager - Fast and simple Node.js version manager, built in Rust",
      "installations": [
        {
          "os": "macos",
          "type": "shell",
          "id": "fnm",
          "source": "curl -fsSL https://github.com/Schniz/fnm/blob/master/.ci/install.sh | bash",
          "postInstall": "fnm install 22 && fnm default 22"
        },
        {
          "os": "linux",
          "type": "shell",
          "id": "fnm",
          "source": "curl -fsSL https://github.com/Schniz/fnm/blob/master/.ci/install.sh | bash",
          "postInstall": "fnm install 22 && fnm default 22"
        }
      ]
    },
    {
      "name": "nvm",
      "description": "Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions",
      "installations": [
        {
          "os": "windows",
          "type": "exe",
          "id": "nvm",
          "source": "https://github.com/coreybutler/nvm-windows/releases/download/1.1.12/nvm-setup.exe",
          "postInstall": "nvm install lts && nvm use node"
        }
      ]
    }
  ]
}
